name:                webnotes
version:             0.1.0.0
github:              "mbrc12/webnotes"
license:             BSD3
author:              "Mriganka Basu Roy Chowdhury"
maintainer:          "mbrc12@gmail.com"
copyright:           "MIT License"

extra-source-files:
    - README.md
    - ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/mbrc12/webnotes#readme>

dependencies:
    - base >= 4.7 && < 5

library:
    source-dirs: src
    dependencies:
        - aeson
        - bytestring
        - conduit
        - conduit-extra
        - pipes
        - pipes-network 
        - cryptohash-sha256
        - directory
        - filepath
        - microstache
        - mtl
        - stm
        - text
        - time
        - turtle
        - unordered-containers
        - network-simple  
        - yaml
        - logging
        - fmt
        - random >= 1.2.0
        # - ekg  

executables:
  webnotes-server:
        main:                Server.hs
        source-dirs:         app
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -main-is Server
        dependencies:
          - optparse-applicative
          - conduit
          - webnotes
          - stm
          - mtl
          - yaml
          - unordered-containers
          - time
          - microstache
          - yaml
          - text
          - filepath
          - directory
          - logging
          - fmt

  webnotes-client:
        main:                Client.hs
        source-dirs:         app
        ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          - -main-is Client  
        dependencies:
          - optparse-applicative
          - conduit
          - webnotes
          - stm
          - mtl
          - yaml
          - unordered-containers
          - time
          - microstache
          - yaml
          - text
          - filepath
          - directory
          - logging
          - fmt
